### ISSUE TITLE
Access Rights 

### ISSUE THREAD

**Issue by jmukiibi** [kavgan/word_cloud#3]
I get this error while trying to install the library: 
ERROR: Command errored out with exit status 128: git clone -q ssh://git@github.com/kavgan/word_cloud.git /private/var/folders/9n/6gbyrw5n2wlg4fc45zpy5yfh0000gn/T/pip-req-build-sz9doyzg Check the logs for full command output

**Comment by kavgan** [comment]
Please try:

```
pip install git+ssh://git@github.com/kavgan/word_cloud.git
```

**Comment by yxyzoe96** [comment]
ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/kavgan/word_cloud.git' /private/var/folders/8s/jr5976ms4fn8xjhfzqnm7hww0000gn/T/pip-req-build-6vhsdt9i Check the logs for full command output.

Get this error as well

**Comment by kavgan** [comment]
Fixed by https://github.com/kavgan/word_cloud/pull/2
